server:
  port: 8082

spring:
  application:
    name: boke-msg

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aurora?serverTimezone=Asia/Shanghai
    username: root
    password: 246810

  # RabbitMQ配置
  rabbitmq:
    host: 117.72.14.87
    port: 5672
    username: blog
    password: N3Qvz2oULujkkx

  # Quartz配置
#  quartz:
#    job-store-type: jdbc
#    properties:
#      org.quartz.jobStore.isClustered: true

  mail:
    host: smtp.qq.com
    username: 3487393070@qq.com
    password: uolitraieemacjdb # 授权码
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true


upload:
  mode: minio
  oss:
    url: http://Bucket域名/
    endpoint: OSS配置endpoint
    accessKeyId: OSS配置accessKeyId
    accessKeySecret: OSS配置accessKeySecret
    bucketName: OSS配置bucketName
  minio:
    url: http://192.168.64.100:9415/
    endpoint: http://117.72.14.87:9415
    accesskey: minioadmin
    secretKey: minioadmin
    bucketName: blog

search:
  mode: elasticsearch

jwt:
  secret: boke

website:
  url: http://127.0.0.1