server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aurora?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: # your_database_username
    password: # your_database_password
    hikari:
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: # your_redis_host
    port: 6477
    password: # your_redis_password
    database: 0
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 100
        max-wait: 10000

  rabbitmq:
    host: # your_rabbitmq_host
    port: 5672
    username: # your_rabbitmq_username
    password: # your_rabbitmq_password
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

  elasticsearch:
    rest:
      uris: # your_elasticsearch_host
      password: # your_elasticsearch_password
      username: # your_elasticsearch_username

  mail:
    host: smtp.qq.com
    username: # your_email
    password: # your_email_authorization_code
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  secret: # your_jwt_secret

search:
  mode: elasticsearch

upload:
  mode: minio
  oss:
    url: # your_bucket_url
    endpoint: # your_oss_endpoint
    accessKeyId: # your_oss_accessKeyId
    accessKeySecret: # your_oss_accessKeySecret
    bucketName: # your_oss_bucketName
  minio:
    url: # your_minio_url
    endpoint: # your_minio_endpoint
    accesskey: # your_minio_accesskey
    secretKey: # your_minio_secretKey
    bucketName: blog

website:
  url: # your_website_url

qq:
  app-id: # your_qq_app_id
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}
